schemaVersion: 2.1.0
metadata:
  name: grpc-with-quarkus
  version: 0.1.0-SNAPSHOT
  icon: https://design.jboss.org/quarkus/logo/final/SVG/quarkus_icon_rgb_default.svg
  tags:
    - Java
    - Quarkus
  projectType: Quarkus
  language: Java

projects:
  - git:
      remotes:
        origin: https://github.com/buuhsmead/grpc-with-quarkus.git
    name: grpc-with-quarkus
    
parent:
  id: java-quarkus
  registryUrl: 'https://registry.devfile.io'
components:
  - name: image-build
    image:
      imageName: java-quarkus-image:latest
      dockerfile:
        uri: src/main/docker/Dockerfile.jvm.staged
        buildContext: .
        rootRequired: false
  - name: kubernetes-deploy
    attributes:
      deployment/replicas: 1
      deployment/cpuRequest: 10m
      deployment/memoryRequest: 100Mi
      deployment/container-port: 8080
    kubernetes:
      uri: deploy.yaml
      endpoints:
        - name: http-8080
          targetPort: 8080
          path: /hello
commands:
  - id: build-image
    apply:
      component: image-build
  - id: deployk8s
    apply:
      component: kubernetes-deploy
  - id: deploy
    composite:
      commands:
        - build-image
        - deployk8s
      group:
        kind: deploy
        isDefault: true    