apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusapp
  title: Example quarkus component for RHDH
  description: |
    This is the example quarkus component for RHDH
  links:
    - title: QuarkusApp Website
      url: https://quarkusapp.example.com
    - title: QuarkusApp Issues
      url: https://jira.quarkusapp.com
    - title: Blog
      url: https://quarkusapp.example.com/blog
    - title: Slack
      url: https://quarkusapp.example.slack.com
  annotations:
    #    argocd/app-name: 'grpc-with-quarkus' # DONOT instead use 'argocd/app-selector'
    # backstage.io/kubernetes-id: 'quarkusapp'
    backstage.io/kubernetes-namespace: 'app-team-b'
    backstage.io/kubernetes-label-selector: 'app=grpc-with-quarkus'
    argocd/app-selector: 'app=grpc-with-quarkus'
    github.com/project-slug: myorg/quarkusapp
    quay.io/repository-slug: myorg/quarkusapp
    backstage.io/techdocs-ref: 'dir:..'
    tekton.dev/cicd : 'true'
    sonarqube.org/project-key: dev-instance/my-project-key
spec:
  type: service
  system: quarkusapp
  owner: quarkusapp-dev-team
  lifecycle: production
  dependsOn:
    - resource:quarkusappdb
  providesApis:
    - openai-api
