apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: quarkusappdb
  title: Example PostgreSQL Database for quarkusapp
  description: PostgreSQL is a powerful, open source object-relational database system.
  links:
    - url: https://www.postgresql.org
      title: PostgreSQL website
      icon: web
    - url: https://postgresql.org/docs
      title: PostgreSQL Documentation
      icon: web
spec:
  type: database
  lifecycle: production
  owner: quarkusapp-dev-team
  system: quarkusapp
