kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: ivs
  # namespace: app-cees-bcu-app
spec:
  hosts:
    - grpc-with-quarkus.app-cees-bcu-app.apps.freubel.sandbox2538.opentlc.com
  gateways:
    - igw
  http:
    - name: http-ingress
      match:
        - uri: # It is important to distinguish between the two ports based on http path!
            exact: /hello
      route:
        - destination:
            host: grpc-with-quarkus.app-cees-bcu-app.svc.cluster.local
            subset: testing
            port:
              number: 8080
    - name: grpc-ingress
      route:
        - destination:
            host: grpc-with-quarkus.app-cees-bcu-app.svc.cluster.local
            subset: testing
            port:
              number: 9000
