apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grpc-with-quarkus
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
  labels:
    app: grpc-with-quarkus
spec:
  destination:
    name: in-cluster
    namespace: app-team-b
  source:
    path: kustomize/base/app
    repoURL: https://github.com/buuhsmead/grpc-with-quarkus.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

# What 'selfHeal: true' does:
# Automatically syncs the cluster state to match Git whenever any drift is detected — no human approval, no visibility into what changed.

# Combined with 'prune: true', any resource created outside Git (e.g., temporary debug pods, metrics sidecars) gets deleted automatically

