kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: route-grpc
  annotations:
    console.alpha.openshift.io/overview-app-route: false
spec:
  path: /
  to:
    kind: Service
    name: grpc-with-quarkus
    weight: 100
  port:
    targetPort: grpc
  wildcardPolicy: None
