kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: route-http
spec:
  path: /
  to:
    kind: Service
    name: grpc-with-quarkus
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
