kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: route-http
  annotations:
    console.alpha.openshift.io/overview-app-route: true
spec:
  path: /
  to:
    kind: Service
    name: grpc-with-quarkus
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
